### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by mysoundmagic** [noumo/easyii-shop#8]
Hi there,

I was trying to install this easyii-shop and easyii-start but whenever i submit the installation form(step2 to step 3) take me to mylocal/admin/install and throws an error web page not found. i tried to googling around but nothing found.  please help, what should i do ?

all requirement passed and mod_rewrite is active. i use apache2 and ubuntu 14.04

**Comment by mkrvevgn** [comment]
I had the same problem (but on Windows).
The problem is here: C:\xampp\htdocs\easyii\vendor\noumo\easyii\views\install\ _form.php
this string:
<?php $form = ActiveForm::begin(['action' => Url::to('/admin/install')]); ?>
must be changed like so:
<?php $form = ActiveForm::begin(['action' => Url::to(['/admin/install'])]); ?>

This problem was solved by author and:
if you download project from author's github
and replace your local version in directory C:\xampp\htdocs\easyii\vendor\noumo\
by dowloaded version all be ok!
